server:
  port: 8080

spring:
  application:
    name: metadataregistry
  datasource:
    url: jdbc:postgresql://localhost:5432/target_db
    username: postgres
    password: kampus
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # validate / update / create / create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# ????????? ????????? RestTemplate (????? HttpClient)
#http:
#  client:
#    connect-timeout: 5000   # 5 ??????
#    read-timeout: 10000     # 10 ??????

# URL ??? Orda API
orda:
  base-url: http://localhost:8585
  token: eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZyIsInN1YiI6InN2cy5uaWsiLCJlbWFpbCI6InN2cy5uaWtAYmsucnUiLCJpc0JvdCI6dHJ1ZSwidG9rZW5UeXBlIjoiQk9UIiwiaWF0IjoxNzU4MDA0NzE0LCJleHAiOm51bGx9.Z9aU428-oa6uHwYSM5xODiQCps6e-1PSSkeebPNNrxtBfapRqtLzgu3K6q9MyVF2fOAxBLr4PrJIjTPz_x5hTuzEjq98TQuoDgFONPJuHW3jr0EkOnOO3dNZc_xKuuLk1GQ8dHDrEH6ImegJFfIy4YrNWesORizHleLZFcsFa9wyj5IjA5LPhZquj3i0whGupuAi9UH1x_q3RjHxFu5foWtCEsqyYk578Ar3H3w_vhu0jzwpJ3o2hNHLVjMCOskcbukbpg0ddFqdas3KNrSe0ho-j1AEmYfr562j4x-QM7GGD5IDTRtDUA2En84RlegzQd6uhcODYW6Pu6IuHmKOeA
  endpoints:
    get:
      services: /api/v1/services/databaseServices
      databases: /api/v1/databases
      schemas: /api/v1/databaseSchemas
      tables: /api/v1/tables

    post:
      databases: /api/v1/databases
      schemas: /api/v1/databaseSchemas
      tables: /api/v1/tables
      services: /api/v1/services/databaseServices

schemas:
  postgres: postgres_metadata
  oracle: oracle_metadata
  mssql: mssql_metadata

http:
  client:
    connect-timeout: 5000
    read-timeout: 10000

logging:
  level:
    root: INFO
