server:
  port: 8080

spring:
  application:
    name: metadataregistry
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_db
    username: postgres
    password: kampus
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # validate / update / create / create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# ????????? ????????? RestTemplate (????? HttpClient)
#http:
#  client:
#    connect-timeout: 5000   # 5 ??????
#    read-timeout: 10000     # 10 ??????

# URL ??? Orda API
orda:
  base-url: http://localhost:8585
  token: eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZyIsInN1YiI6InN2cy5uaWsiLCJlbWFpbCI6InN2cy5uaWtAYmsucnUiLCJpc0JvdCI6dHJ1ZSwidG9rZW5UeXBlIjoiQk9UIiwiaWF0IjoxNzU4MjY3ODExLCJleHAiOm51bGx9.bKBcLnUmIY28JyTfdbLmq1iHtk3fNyxYFO3xIxhaLut5f17Bo0kvXvwF9KYqsoepI5wyEU2MG9BlFvTlU3uwQMlFmrRk8VrE_hbrYhhUfiBKUy_TXxonrXQsETGY9RyG9Phhg1AGPerjhUO5D7Bsaz52fKWHktbCSYFA3ytRYh1mqfbGLQ6N31bu1wNSlA1jGaawCpoj7ikqR9haZ0WNeiGx4F7M2KzR-2bQjPhy7ebWVY80_J3umBg7zK_Lty5hHgS4qtaAZR2TYvs9OEou-CXbw44GLDmNJq2v3tkeEriX-XQolPrgcxPQoBJEBqxWqpGeZIMSirLe2a8F1tZvzw
  endpoints:
    get:
      services: /api/v1/services/databaseServices
      databases: /api/v1/databases
      schemas: /api/v1/databaseSchemas
      tables: /api/v1/tables

    post:
      databases: /api/v1/databases
      schemas: /api/v1/databaseSchemas
      tables: /api/v1/tables
      services: /api/v1/services/databaseServices

schemas:
  postgres: postgres_metadata
  oracle: oracle_metadata
  mssql: mssql_metadata

http:
  client:
    connect-timeout: 5000
    read-timeout: 10000

logging:
  level:
    root: INFO
